language: c
services:
    - docker
os:
  - linux-ppc64le
dist: xenial      
sudo: false

env:
    matrix:
        #- ITEST_TARGET=itest_trusty
        # - ITEST_TARGET=itest_xenial
        #- ITEST_TARGET=itest_bionic
        - ITEST_TARGET=itest_jessie
        #- ITEST_TARGET=itest_stretch
        #- ITEST_TARGET=itest_tox

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name $GITHUB_USER_NAME #"YOUR GIT USER NAME"
      - git config --local user.email $GITHUB_USER_EMAIL #"YOUR GIT USER EMAIL"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY #"GITHUB OAUTH TOKEN"
  file: "dist/dumb-init_1.2.1_ppc64el.deb"
  skip_cleanup: true
  on:
    tags: true

script:
   - make "$ITEST_TARGET"


#after_success: |
#  if [ -n "$GITHUB_API_KEY" ]; then
#    cd "$TRAVIS_BUILD_DIR"
#    # This generates a `web` directory containing the website.
#    make web
#    cd web
#    git init
#    git checkout -b gh-pages
#    git add .
#    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
#    git push -f -q https://ghatwala:$GITHUB_API_KEY@github.com/ghatwala/dumb-init-gh-pages gh-pages &2>/dev/null
#    cd "$TRAVIS_BUILD_DIR"
#  fi
